// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { resolve } from "path";
dotenv.config({ path: resolve(process.cwd(), ".env.local") });
dotenv.config({ path: resolve(process.cwd(), ".env"), override: false });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {

    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["POSTGRES_URL_NON_POOLING"] || process.env["POSTGRES_PRISMA_URL"] || process.env["DATABASE_URL"],
  },
});
